spring.application.name=firstproject
server.port=${PORT:9000}

# Gmail API credentials file
gmail.credentials.path=classpath:credentials.json
gmail.client.id=${YOUR_CLIENT_ID}
gmail.client.secret=${YOUR_CLIENT_SECRET}


# File upload configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
file.upload-dir=uploads/resumes/